version: '3'

networks:
    main:

services:
    php:
        build: ./docker
        container_name: php
        networks:
            main:
                aliases:
                    - php
        user: 1000:1000
        expose:
            - 9000
        volumes:
            - "./apps:/project"

    web:
        image: nginx:1.17-alpine
        container_name: web
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - "./apps:/project"
            - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro"
        networks:
            main:
                aliases:
                    - web